// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3M-tz380y9cBCLwCevbKvnoT9RTeEecQ',
    appId: '1:785335134912:web:e94f21a9680fda52d01b25',
    messagingSenderId: '785335134912',
    projectId: 'talklytic131',
    authDomain: 'talklytic131.firebaseapp.com',
    storageBucket: 'talklytic131.appspot.com',
    measurementId: 'G-B60GHDSK4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ECm268qEaaWM4US4PiK3wkBlxwxK6Uc',
    appId: '1:785335134912:android:34a98c3682d6f711d01b25',
    messagingSenderId: '785335134912',
    projectId: 'talklytic131',
    storageBucket: 'talklytic131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzBW3LrtfVdUyv0EJdny5vvW93toAjPuw',
    appId: '1:785335134912:ios:12e9a90fef9f4d9ed01b25',
    messagingSenderId: '785335134912',
    projectId: 'talklytic131',
    storageBucket: 'talklytic131.appspot.com',
    iosBundleId: 'com.example.talklytic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzBW3LrtfVdUyv0EJdny5vvW93toAjPuw',
    appId: '1:785335134912:ios:9cda4cbe4552eef6d01b25',
    messagingSenderId: '785335134912',
    projectId: 'talklytic131',
    storageBucket: 'talklytic131.appspot.com',
    iosBundleId: 'com.example.talklytic.RunnerTests',
  );
}
