// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRMvwxeKFG-qLxluZ1BwMBROnJJF52xHw',
    appId: '1:178302982904:web:f57d838c82c9ff31e0790d',
    messagingSenderId: '178302982904',
    projectId: 'talklytic',
    authDomain: 'talklytic.firebaseapp.com',
    storageBucket: 'talklytic.appspot.com',
    measurementId: 'G-DDQ1WSFSRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTzr7U4K-3KtneFOtwojj1H-2LPFjQEwQ',
    appId: '1:178302982904:android:13d9cf1c00a2c0c6e0790d',
    messagingSenderId: '178302982904',
    projectId: 'talklytic',
    storageBucket: 'talklytic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdI42YdbTjnnsc04qsJBu3q8cqQJmsEok',
    appId: '1:178302982904:ios:f3e5b5ba419d36c9e0790d',
    messagingSenderId: '178302982904',
    projectId: 'talklytic',
    storageBucket: 'talklytic.appspot.com',
    iosBundleId: 'com.example.talklytic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdI42YdbTjnnsc04qsJBu3q8cqQJmsEok',
    appId: '1:178302982904:ios:fff7613005079403e0790d',
    messagingSenderId: '178302982904',
    projectId: 'talklytic',
    storageBucket: 'talklytic.appspot.com',
    iosBundleId: 'com.example.talklytic.RunnerTests',
  );
}
